version: '2'
services:
  wp_ftp:
    build:
      context: .
    environment: 
      - FTP_USER=newuser
      - FTP_PASSWORD=password
      - WORDPRESS_ROOT=/var/www/html
    ports:
      - "8080:80"
      - "21:21"
